ANCHORS:
  node_steps: &node_steps
    steps:
      - checkout
      - run: npm install
      # Check whether "run build" is successful
      - run: npm run build
      - run: npm test
      - run:
          name: Executable test
          command: |
            set -x
            project_path=$PWD
            # Make test environment
            mkdir /tmp/test_env
            cd /tmp/test_env
            # Install this project
            npm i -S $project_path
            # Execute help
            ./node_modules/.bin/piping-url-agent --help

version: 2
jobs:
  node_10:
    docker:
      - image: circleci/node:10
    <<: *node_steps

  node_8:
    docker:
      - image: circleci/node:8
    <<: *node_steps

workflows:
  version: 2
  node_tests:
    jobs:
      - node_10
      - node_8
